### ISSUE TITLE
Operations on Invalid Watchers Must Throw

### ISSUE THREAD

**Issue by bwoebi** [async-interop/event-loop#58] opened 2016-05-23 21:54 UTC
From #53:

> May we please add that cancel()'ling multiple times or any other operation on already invalid watchers is disallowed (as watcher ids may be reused)?
> Calling unreference(), reference(), enable() and disable() multiple times must not error.

Is everyone okay with that (I'll open a PR tomorrow to add that in docblocks)? Or are there issues here?

**Comment by kelunik** [comment] 2016-05-24 11:50
So you want to throw an exception then? We should then also throw exceptions if `unreference` etc. are called with an non-existent watcher.

**Comment by bwoebi** [comment] 2016-05-24 12:14
For non-existent watchers, sure. Passing these is a mistake which may in edge cases even alter the behavior of the program when the watcher id gets reused.

**Comment by kelunik** [comment] 2016-05-26 14:33
If you think it's a duplicate of #61, then I'll give this one a better title.

**Comment by bwoebi** [comment] 2016-05-26 16:25
PR is at #63.

**Comment by joshdifabio** [comment] 2016-05-27 11:24
Is there any reason `cancel()` can't be idempotent? (I.e. perform a null-op when watcherId doesn't exist instead of throwing.) I can't think of any reason I'd want it to throw in such cases.

**Comment by bwoebi** [comment] 2016-05-27 11:28
> as watcher ids may be reused

This is the main point. If a watcher id gets reused, you may end up with actually cancelling another watcher than you intended. Thus doubly cancelling or operations on invalid watchers must be a programmer error. (which typically happens spuriously, i.e. if you use spl_object_hash() internally as id; thus very bad.)

**Comment by joshdifabio** [comment] 2016-05-27 12:34
Is this definitely preferable to requiring that watcher ID's be unique for the duration of the process?

To allow unique watcher ID's across all drivers, the drivers could return watcher ID's which are unique per-driver instance and `Loop` could prepend those ID's with a driver ID (something to uniquely identify a driver instance). This would ensure that the watcher ID's returned by `Loop` were unique for the duration of the process. It could also mean we don't have really long strings (from `spl_object_hash`) being stored all over the place, although I don't know how important that actually is.

Edit: I'm assuming that _drivers could return watcher ID's which are unique per-driver instance_ would be fairly straightforward if a counter was used.

**Comment by bwoebi** [comment] 2016-05-27 12:50
Actually, I think I'm possibly wrong here...

just use a `static $watcher = "a";` which you can increment on every assign … is unique and the strings are short enough …
After a _hundred trillion_ of watchers you still only have 10 chars … and 10 chars will probably cover the life-time of a server… (i.e. 11 chars are enough for 10 million watchers per second for 11 years.)

And as we don't need unpredictability of watcher ids here, this should be fine …

So, let me revert this commit and redecide… I've merged too quickly, indeed.

**Comment by joshdifabio** [comment] 2016-05-27 12:54
Good point, a single static counter would be a much more elegant implementation. Could even have a new method on `Loop`:

``` php
public static function nextWatcherId() : string;
```

**Comment by bwoebi** [comment] 2016-05-27 12:58
Do we need to have a global counter? A counter per driver should be good enough?

**Comment by joshdifabio** [comment] 2016-05-27 13:01
I was assuming we'd want to guarantee that the methods on `Loop` return a unique (for the duration of the process) watcher ID. Unless we do something like I suggested in my earlier comment where we concatenate a driver instance ID and a driver watcher ID, but I figured it'd be more elegant (and efficient?) to have a single global counter (which is actually what I thought you were suggesting).

**Comment by bwoebi** [comment] 2016-05-27 13:03
That way we'd be introducing a dependency on the Loop class from within the driver implementations; which both should be rather decoupled...

**Comment by joshdifabio** [comment] 2016-05-27 13:05
That's true, although the driver implementations will be in packages which depend on this package anyway, so I don't know how much difference that would really make. Applying GRASP (high cohesion) would seem to suggest that such a method might belong in the `Loop` class at least.

Just so I understand, are you thinking that watcher ID's returned by `Loop` _should_ be unique for the duration of the process, or just unique to the current driver?

**Comment by bwoebi** [comment] 2016-05-27 13:13
I'm not sure about unique for a process.
But they definitely must then be unique per driver.

Perhaps we want to have a tiny function (which then would be unique per process):

``` php
function nextWatcherId() {
    static $id = "a";
    return $id++;
}
```

But independent of the loop, just a standalone function whose output is guaranteed to not have appeared yet.

**Comment by joshdifabio** [comment] 2016-05-27 13:14
Personally, I think that would be a good solution. Guaranteeing uniqueness for the duration of the process is IMO good to do given that it's so easy.

**Comment by trowski** [comment] 2016-05-27 13:58
I think a unique watcher ID per driver would be sufficient, though as @bwoebi pointed out, a function would work, but this is something that `Loop` should not provide in my opinion.

Using an invalid watcher ID generally represents a programming error, so I think throwing makes a lot of sense when an operation is attempted with an invalid ID.

**Comment by bwoebi** [comment] 2016-05-27 14:03
Double cancel() may though not be a programming error, just like double Loop::stop() may not be. (e.g. whatever Awaitable resolves first, will cancel first, the second Awaitable will also cancel. This prevents the need of a shared variable to mark the watcher as already cancelled.)

Using an _invalid_ watcher id (i.e. one which may _never_ be valid until now) _MUST_ throw.

**Comment by bwoebi** [comment] 2016-05-27 14:07
@trowski The only thing I may agree that we throw here, is enable() on a cancel()'led watcher.
This one actually has influence on whether the program continues to work or not (example: call enable on cancelled watcher, return an Awaitable, which then never gets resolved as the watcher is never called)

But disable() on a cancel()'led watcher is IMO equivalent to disable()'ing an already disable()'d watcher. These shall be idempotent.
At least as long as there is no particular technical reason against that, I don't see why it should throw.

**Closed as completed** 2016-06-06 03:44 UTC
Labels: discussion, has pull-request
