### ISSUE TITLE
Operations on Invalid Watchers Must Throw

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop#61] opened 2016-05-26 14:28 UTC
All operations like `disable`, `enable`, `cancel` with an invalid (non-existent) watcher ID MUST throw an exception. We need to add it to the phpDoc and create a base exception for that.

**Comment by bwoebi** [comment] 2016-05-26 14:30
Duplicate of #58.

**Closed as completed by bwoebi** 2016-05-26 14:30 UTC
Labels: help wanted, needs pull-request
