### ISSUE TITLE
Loop bound state

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop#25] opened 2016-05-12 15:19 UTC
_Moved from https://github.com/async-interop/event-loop/issues/14#issuecomment-198793124_.

We need some mechanism to store global state bound to a loop. This can be used for things like a default DNS resolvers or filesystem drivers.

Since we have I/O bound applications, most operations will have something to do with networking operations. Most of these need DNS, so it might make sense to have a global accessor for DNS just like for the event loop itself.

Otherwise it's possible to pass it optional and create a new one if no resolver is specified. Multiple instance aren't a problem for DNS, just for the event loop.

As already written to @AndrewCarterUK in private:

> e.g. you open a DNS connection and store the connection globally, because DNS is something you want globally in your application, because not every socket should have to deal with an injected resolver. If you swap the event loop now and make another DNS lookup, it will use the same connection, but will never receive a read event, since the event loop that could trigger that read isn't currently running.

If the connection is bound to the loop, it would just create a new connection once the loop is swapped.

**Comment by bwoebi** [comment] 2016-05-12 15:23
I totally agree this should be a thing. Avoids having to manually reset all the global loop-bound instances upon each event loop swap.

The manual resetting has proven to be forgotten often from experience (especially in tests) and really should be solved at the Loop level. While not strictly necessary, it's a major usability issue.

**Comment by kelunik** [comment] 2016-05-12 15:42
Note: This must be handled by the accessor only.

**Comment by sagebind** [comment] 2016-05-12 15:44
Hmm, interesting idea. Should there be some sort of "registry" that is used to store these things? Essentially it gets turned into a service locator, which some people dictate is "always bad".

**Comment by bwoebi** [comment] 2016-05-12 15:50
@coderstephen No, it's not a service locator, but rather a global, just reactor bound. A service locator is meant to be accessed by other entities.

In this case the state is to be fetched by functions (i.e. in DNS we have query() and resolve()), looks like this then:

``` php
function query($query) {
   return Loop::getState("amp.dns")->query($query);
}
```

Outside entities shall never access foreign state.

In general, it's applicable everywhere where you have statics or globals currently.

**Comment by kelunik** [comment] 2016-05-12 15:51
It's always bad except when it's not.

With Amp, there are only two use cases for such a thing currently: DNS and Filesystem.

**Comment by sagebind** [comment] 2016-05-12 16:04
When I called service locators "always bad", it was a bit tongue in cheek. :grinning:

So the idea then is to also reset any additional bound states whenever the loop is also reset or discarded?

**Comment by bwoebi** [comment] 2016-05-12 16:06
@coderstephen exactly that. (and state is put back in case of event loop nesting and you quit the nested loop)

**Comment by kelunik** [comment] 2016-05-13 19:12
You can find a possible PR in #31.

**Comment by rdlowrey** [comment] 2016-05-16 11:31
Service locators are unambiguously suboptimal. I would say, however, that there is no good or bad but thinking makes it so :)

That said, this isn't a service locator. It's just a loop-local "global" data store as Bob mentioned. Under normal circumstances I would run away in terror from this kind of suggestion, however the rules are slightly different for the kind of work we're doing here. The issue we encounter is that our event loop work is very much below the application level. Most of the work we're doing here is at the systems level; it's sub-application layer and in order to make it useful in real world software systems we have to engage in some hand-wavy black magic from time to time.

The event loop is very much its own VM execution environment and as such there are certain systems-level things it has to coordinate or you force applications to know every implementation detail of how to perform even the most basic network operation.

But the problem with a registry is people _always_ misuse it. It's the same reason why php.ini is horrible today ... registries are always a bad idea. I'm not sure what the best solution is here. It's a difficult problem to solve elegantly.

**Comment by bwoebi** [comment] 2016-05-17 22:24
@rdlowrey The people who misuse `global` or `static` are the same ones who also would misuse our Registry. There's not a lot we can do about that. Except maybe clashing some warning about what to not do.

The issue is that there's not much of an alternative. I think the proposed implementation (as in PR #31) is the cleanest you can get here.

**Comment by bwoebi** [comment] 2016-05-19 13:52
Closing as PR #31 has been merged.

**Closed as completed by bwoebi** 2016-05-19 13:52 UTC
Labels: discussion
